branches:
  except:
    - gh-pages
language: perl6
sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libsamplerate0-dev
  - sudo apt-get install -qq -y libsndfile1-dev
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef --deps-only install .
